version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ildar"
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres